//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlexDaemonsetTemplate) DeepCopyInto(out *FlexDaemonsetTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlexDaemonsetTemplate.
func (in *FlexDaemonsetTemplate) DeepCopy() *FlexDaemonsetTemplate {
	if in == nil {
		return nil
	}
	out := new(FlexDaemonsetTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlexDaemonsetTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlexDaemonsetTemplateList) DeepCopyInto(out *FlexDaemonsetTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FlexDaemonsetTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlexDaemonsetTemplateList.
func (in *FlexDaemonsetTemplateList) DeepCopy() *FlexDaemonsetTemplateList {
	if in == nil {
		return nil
	}
	out := new(FlexDaemonsetTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlexDaemonsetTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlexDaemonsetTemplateSpec) DeepCopyInto(out *FlexDaemonsetTemplateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlexDaemonsetTemplateSpec.
func (in *FlexDaemonsetTemplateSpec) DeepCopy() *FlexDaemonsetTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(FlexDaemonsetTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlexDaemonsetTemplateStatus) DeepCopyInto(out *FlexDaemonsetTemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlexDaemonsetTemplateStatus.
func (in *FlexDaemonsetTemplateStatus) DeepCopy() *FlexDaemonsetTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(FlexDaemonsetTemplateStatus)
	in.DeepCopyInto(out)
	return out
}
