apiVersion: v1
kind: Namespace
metadata:
  name: flexdaemonsets-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flexdaemonsets-webhook-sa
  namespace: flexdaemonsets-system # Deploy webhook components in their own namespace
---
# ClusterRole "flexdaemonsets-webhook-role" is removed as its permissions are a subset of "manager-role"
# and the ClusterRoleBinding "flexdaemonsets-webhook-binding" will now point to "manager-role".
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flexdaemonsets-webhook-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role # Changed from flexdaemonsets-webhook-role
subjects:
- kind: ServiceAccount
  name: flexdaemonsets-webhook-sa
  namespace: flexdaemonsets-system
